name: 'telegram_bot_cli'
description: 'A sample command-line application.'
version: '1.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_bot_library:
    hosted: 'https://package-repository-general-developer.vercel.app/package/repository/dart'
    version: '^0.0.0'
  general_universe:
    hosted: 'https://package-repository-general-developer.vercel.app/package/repository/dart'
    version: '^0.0.0'
  packagex:
    hosted: 'https://package-repository-general-developer.vercel.app/package/repository/dart'
    version: '^0.0.0'
  path: '^1.9.0'
  server_universe:
    hosted: 'https://package-repository-general-developer.vercel.app/package/repository/dart'
    version: '^0.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
funding: []
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
