name: 'edge_user_and_bot_app'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  cupertino_icons: '^1.0.8'
  database_universe:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  database_universe_flutter_libs:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  flutter:
    sdk: 'flutter'
  general_audio_flutter:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  general_bot_library:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  general_bot_library_flutter:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  general_universe:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  general_universe_flutter:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  media_universe_flutter:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  packagex:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  path: '^1.9.0'
  server_universe:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  system_information:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  system_information_flutter:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  url_launcher: '^6.3.1'
dev_dependencies:
  build_runner: 'any'
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
  msix: '^3.16.8'
flutter:
  uses-material-design: true
project:
  type: 'opensource'
  is_use_direct_package: true
  is_private: true
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
funding: []
packagex:
  name: 'edge_user_and_bot_app'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_build_arguments: []
  dart_compile_exe_arguments: []
  uploads:
    - platform_type: 'github'
      github_username: 'archivon-apps-stores'
      github_tag: 'release'
      github_is_org: false
      github_repository_name: 'edge_user_and_bot_app'
    - platform_type: 'supabase'
      supabase_folder_name: 'release'
    - platform_type: 'telegram'
      telegram_chats:
        - chat_id: '@slebew'
          message_thread_id: ''
  packages:
    - dart_target: 'edge_user_and_bot_app'
      flutter_target: 'main'
      dart_name: 'edge_user_and_bot_app'
      flutter_name: 'edge_user_and_bot_app'
      output_name: 'edge-user-and-bot-app'
      is_edge: false
      is_edge_debug: false
      is_edge_build_vercel: false
      is_edge_build_supabase: false
      is_edge_build_cloudflare: false
      is_edge_build_netlify: false
msix_config:
  display_name: 'edge_user_and_bot_app'
  install_certificate: false
