name: 'general_bot_library'
description: 'GGML Is Library machine learning in dart with special feature speed up inference model in cpu only or any gpu'
version: '0.0.0'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/general_bot_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'general'
  - 'bot'
  - 'userbot'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '^1.19.0'
  ffi: '^2.1.4'
  general_universe:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
  http: '^1.3.0'
  mime: '^2.0.0'
  path: '^1.9.0'
  server_universe:
    hosted: 'https://package-repository-general-developer.vercel.app'
    version: '^0.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
flutter:
  uses-material-design: true
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: 'azkadev'
      note: ''
      social_medias:
        - 'https://github.com/azkadev'
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
