name: 'general_bot_library'
description: 'GGML Is Library machine learning in dart with special feature speed up inference model in cpu only or any gpu'
version: '0.0.10'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/general_bot_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'general'
  - 'bot'
  - 'userbot'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  ffi: '^2.1.4'
  http: '^1.3.0'
  path: '^1.9.0'
  io_universe: '^0.0.8'
  mime: '^2.0.0'
  general_lib: '^0.0.71'
  collection: '^1.19.0'
  server_universe: '^0.0.38'
  ffi_universe: '^0.0.8'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
flutter:
  uses-material-design: true
project:
  type: ''
